# https://hub.docker.com/_/python
FROM python:3.10
MAINTAINER AlexNeStu

WORKDIR /pypi

# OS dependencies
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    software-properties-common sudo curl \
    zsh git unzip zip nload tree mc lsof net-tools nano \
    build-essential libpcre3-dev libz-dev default-libmysqlclient-dev \
    libatlas-base-dev gfortran nginx supervisor

# ZSH
RUN git config --global init.defaultBranch master
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/\
ohmyzsh/master/tools/install.sh)" "" --unattended \
    && chsh -s $(which zsh)
SHELL ["/bin/zsh", "-c"]


#  App dependencies
RUN pip3 install --upgrade pip glances poetry uwsgi httpie


# Poetry ,venv install
COPY poetry.lock /tmp
COPY pyproject.toml /tmp
RUN poetry config virtualenvs.in-project true && cd /tmp && poetry install
RUN echo "\nsource /tmp/.venv/bin/activate" >> ~/.zshrc
RUN source /tmp/.venv/bin/activate
