version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-new
    environment:
      - IS_DEPLOY=1
    ports:
      - '8080:5000'
    restart: 'no'
    tty: true
    volumes:
      - '.:/pypi'
    depends_on:
      - db
  db:
    container_name: db
    image: "mongo"
