version: '3'
services:
  api:
    container_name: flask-container
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: python app.py
    env_file:
      - app.env
    depends_on:
      - redis
    ports:
      - '5000:5000'
    restart: 'no'
    tty: true
  redis:
    image: redis
    container_name: redis-container
    environment:
      - TEST=1
    ports:
      - '6379:6379'