[tool.poetry]
name = "proj"
version = "0.1.0"
description = ""
authors = ["Alexander Nesterovich <a.v.nesterovich@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
