"""Add Audit table cls

Revision ID: f9301658eebc
Revises: ffd2e0438799
Create Date: 2022-01-25 18:09:17.960504

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f9301658eebc'
down_revision = 'ffd2e0438799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_audit_created_date'), 'audit', ['created_date'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_created_date'), table_name='audit')
    op.drop_table('audit')
    # ### end Alembic commands ###
