"""Added last_updated column to Package cls

Revision ID: ffd2e0438799
Revises: 
Create Date: 2022-01-25 16:37:17.581161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ffd2e0438799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('last_updated_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_packages_last_updated_date'), 'packages', ['last_updated_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_last_updated_date'), table_name='packages')
    op.drop_column('packages', 'last_updated_date')
    # ### end Alembic commands ###
