version: '3'
services:
  os:
    build:
      context: .
    container_name: os
    environment:
      - IS_DEPLOY=0
    ports:
      - '8080:5000'
    # entrypoint: /bin/zsh -c "/bin/zsh -c \"$${@}\""
    command: /bin/zsh -c "
        source /pypi/.venv/bin/activate && cd /pypi/pypi_org &&
        python3 app.py run --port=5000 --host=0.0.0.0 --without-threads"