# Need to find the volumes and remove it after e.g. password changed ${DB_USER_PASSWORD}
version: "3.9"

services:

  db-mysql:
    # mycli --port 3307 -u root -p $DB_USER_PASSWORD
    image: mysql:8.2
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - db-mysql:/var/lib/mysql

  db-postgresql:
    # sudo pgcli -h /var/lib/docker/volumes/common_db-postgresql-socket/_data -d $DB_NAME'
    image: postgres:16
    container_name: db-postgresql
    environment:
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-postgresql-data:/var/lib/postgresql/data
      - db-postgresql-socket:/var/run/postgresql

  db-redis:
    # iredis -a $DB_USER_PASSWORD
    image: redis:7.2.3
    container_name: db-redis
    environment:
      TEST: TEST1
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_USER_PASSWORD}
    volumes:
      - db-redis:/data
#    sysctls:
#      # https://github.com/jemalloc/jemalloc/issues/1328
#      # To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
#      - vm.overcommit_memory=1

  db-mongodb:
    image: mongo
    container_name: db-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - db-mongodb:/data/db


# /var/lib/docker/volumes/
volumes:
  db-mysql:
  db-postgresql-data:
  db-postgresql-socket:
  db-redis:
  db-mongodb: