# Need to find the volumes and remove it after e.g. password changed ${DB_USER_PASSWORD}
version: "3.9"

services:

  db-mysql:
    image: mysql:8.2
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - db-mysql-vol:/var/lib/mysql

  db-postgresql:
    image: postgres:16
    container_name: db-postgresql
    environment:
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-postgresql-vol:/var/lib/postgresql/data

  db-redis:
    image: redis:7.2.3
    container_name: db-redis
    environment:
      TEST: TEST1
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_USER_PASSWORD}
    volumes:
      - db-redis:/data
#    sysctls:
#      # https://github.com/jemalloc/jemalloc/issues/1328
#      # To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
#      - vm.overcommit_memory=1

# /var/lib/docker/volumes/
volumes:
  db-mysql-vol:
  db-postgresql-vol:
  db-redis: