# Need to find the volumes and remove it after e.g. password changed ${DB_USER_PASSWORD}
version: '3.9'

services:

  # mycli --port 3307 -u root -p $DB_USER_PASSWORD
  db-mysql:
    # https://dev.mysql.com/doc/relnotes/mysql/8.2/en/
    image: mysql:8.2
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - db-mysql:/var/lib/mysql


  # sudo pgcli -h /var/lib/docker/volumes/common_db-postgresql-socket/_data -d $DB_NAME'
  db-postgresql:
    # https://www.postgresql.org/docs/release/
    image: postgres:16
    container_name: db-postgresql
    environment:
      POSTGRES_USER: ${DB_ADMIN_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-postgresql-data:/var/lib/postgresql/data
      - db-postgresql-socket:/var/run/postgresql

  # iredis -a $DB_USER_PASSWORD
  db-redis:
    # https://docs.redis.com/latest/rs/release-notes/
    image: redis:7.2.3
    container_name: db-redis
    environment:
      TEST: TEST1
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${DB_USER_PASSWORD}
    volumes:
      - db-redis:/data
#    sysctls:
#      # https://github.com/jemalloc/jemalloc/issues/1328
#      # To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
#      - vm.overcommit_memory=1

  db-mongodb:
    # https://www.mongodb.com/docs/v7.0/release-notes/
    image: mongo:7.0.2
    container_name: db-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_COLLECTION: ${DB_COLLECTION}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - db-mongodb:/data/db
    env_file:
      - .env


# /var/lib/docker/volumes/
volumes:
  db-mysql:
  db-postgresql-data:
  db-postgresql-socket:
  db-redis:
  db-mongodb: